import { LegalPage } from "@/components/LegalPage";
import { Fill } from "@/components/LegalFill";

export const metadata = { title: "Privacy — Bounce" };

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Legal" title="Privacy Policy" updated="[DATE YOU PUBLISH THIS]">
        <p>
          This describes exactly what Bounce&rsquo;s code actually collects and does with it — not boilerplate. Fill
          in the bracketed fields (like <Fill>Your Company Name</Fill>) with your real details, and have a lawyer
          confirm this matches your obligations wherever your users are (GDPR if you have EU users, CCPA if you have
          California users, etc.) before you rely on it.
        </p>

        <h2>1. Who this is</h2>
        <p>
          This policy covers Bounce, operated by <Fill>Your Company Name / Your Legal Name</Fill>. Contact:{" "}
          <Fill>privacy@yourdomain.com</Fill>.
        </p>

        <h2>2. What we collect</h2>
        <h3>If you just use Bounce as a guest (no account)</h3>
        <ul>
          <li>
            <strong>A device identifier</strong> — a random ID generated in your browser&rsquo;s local storage the
            first time you visit, so we can keep your coin balance and moderation history tied to your device without
            asking for anything from you.
          </li>
          <li>
            <strong>A signed session cookie</strong> (<code>bounce_session</code>) — httpOnly, first-party, identifies
            your session to our server. It contains no personal information by itself, just a signed reference to
            your guest or account record.
          </li>
          <li>
            <strong>A hashed IP address</strong> — your IP is run through a one-way salted hash before it&rsquo;s
            stored; we never store your raw IP address. It&rsquo;s used only for ban enforcement (blocking abusive
            devices/networks) and basic abuse prevention.
          </li>
        </ul>
        <h3>If you create an optional account</h3>
        <ul>
          <li>Your email address, or your Google account&rsquo;s email and profile info if you sign in with Google.</li>
          <li>Anything you choose to add to your profile: a display name, an emoji avatar, default interest tags, your gender (only if you set it, used solely for match filtering).</li>
        </ul>
        <h3>Generated by using the product</h3>
        <ul>
          <li>Coin balance and a log of coin transactions (purchases, spends, rewards) — no payment card details, those go straight to Stripe (see §5).</li>
          <li>
            Chat session metadata: when a match started/ended, whether it was video or text, which interest tags
            matched, and how it ended (skipped, reported, etc.) — <strong>never the video, audio, or text content of
            your chats.</strong> Text chat during a random match is relayed live and is not stored.
          </li>
          <li>
            Reports you file or that are filed against you, and any resulting moderation action (warning, ban tier).
          </li>
          <li>
            Moderation scan results: our automated screening scores a downscaled snapshot of your outgoing video
            periodically during a call. We store only the resulting score and a one-way hash of that snapshot — never
            the image itself, which is discarded immediately after scoring.
          </li>
          <li>
            If you use Friends/DM: the fact that two accounts are friends, and the actual text of direct messages
            sent between friends (these are not anonymous/ephemeral like random chat — they&rsquo;re a real inbox,
            stored so you can read your conversation history).
          </li>
          <li>Referral relationships (who invited whom) if you use a referral link.</li>
          <li>Daily visit timestamps, used only to calculate your streak.</li>
        </ul>

        <h2>3. What we deliberately do not collect</h2>
        <ul>
          <li>We never record or store the video or audio of your calls. Calls are peer-to-peer or relayed live through a TURN server when needed for connectivity — the server never saves the stream.</li>
          <li>We never store your raw IP address, only a salted hash of it.</li>
          <li>We never store the actual image from a moderation scan, only its score and a hash.</li>
          <li>We don&rsquo;t store your payment card details — Stripe handles and stores those under its own security standards.</li>
        </ul>

        <h2>4. Cookies and local storage</h2>
        <p>
          Bounce uses one first-party session cookie (<code>bounce_session</code>) and, if you sign in, a session
          cookie set by our authentication provider (NextAuth). Your browser&rsquo;s local storage holds your device
          ID and small UI preferences. We do not use third-party tracking or advertising cookies today.{" "}
          <Fill>
            Update this section if/when you add an ad network — most ad networks set their own tracking cookies and
            you&rsquo;ll need to disclose that here and likely add a cookie-consent banner depending on your
            audience&rsquo;s location.
          </Fill>
        </p>

        <h2>5. Who we share data with</h2>
        <ul>
          <li><strong>Stripe</strong> — processes coin and subscription payments. Stripe receives your payment details directly; we receive only confirmation that a payment succeeded.</li>
          <li><strong>Google</strong> — if you choose to sign in with Google, Google provides us your email/profile per its own terms.</li>
          <li>
            <Fill>Your email provider (if you enable email sign-in)</Fill> — sends magic-link sign-in emails on our
            behalf.
          </li>
          <li>
            <Fill>Your hosting provider (e.g. Hetzner/DigitalOcean)</Fill> — hosts the server and database this data
            lives on.
          </li>
          <li>
            We report confirmed child-safety violations to the National Center for Missing &amp; Exploited Children
            (NCMEC) as legally required — see the <a href="/terms">Terms</a> §11.
          </li>
          <li>We do not sell your personal information.</li>
        </ul>

        <h2>6. How long we keep it</h2>
        <p>
          Guest and account records, coin history, and moderation/ban records are kept for as long as your
          account/device is active, and for a reasonable period after to enforce bans and prevent abuse evasion.
          Direct messages are kept until you or the recipient are no longer friends, or you request deletion. You can
          request deletion of your account and associated data at any time (see §7).
        </p>

        <h2>7. Your rights</h2>
        <p>
          Depending on where you live, you may have rights to access, correct, export, or delete your personal data,
          and to object to or restrict certain processing. To exercise any of these, contact{" "}
          <Fill>privacy@yourdomain.com</Fill>. We&rsquo;ll respond within{" "}
          <Fill>the timeframe your applicable law requires, e.g. 30 days</Fill>. Note that some data (like ban
          records) may be retained even after a deletion request where necessary for safety, security, or legal
          compliance.
        </p>

        <h2>8. Children&rsquo;s privacy</h2>
        <p>
          Bounce is strictly for people 18 and older (see <a href="/terms">Terms</a> §2) and is not directed at
          children. We do not knowingly collect data from anyone under 18. If we learn that we have, we will delete
          it and take action on the associated account/device.
        </p>

        <h2>9. Security</h2>
        <p>
          Session identifiers are cryptographically signed, IP addresses and moderation snapshots are hashed rather
          than stored raw, and payment data never touches our servers directly. No system is perfectly secure; if you
          believe you&rsquo;ve found a vulnerability, report it to <Fill>security@yourdomain.com</Fill>.
        </p>

        <h2>10. International data transfers</h2>
        <p>
          Bounce&rsquo;s servers are located in <Fill>the country/region your VPS is in</Fill>. If you access Bounce
          from elsewhere, your data will be transferred to and processed there.{" "}
          <Fill>Add specific transfer-mechanism language here (e.g. SCCs) if you have EU users and need it.</Fill>
        </p>

        <h2>11. Changes to this policy</h2>
        <p>
          We&rsquo;ll update the date at the top of this page when this policy changes, and flag material changes
          more visibly before they take effect.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about this policy or your data: <Fill>privacy@yourdomain.com</Fill>.
        </p>
    </LegalPage>
  );
}
